name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn  # Enables caching for Yarn dependencies

      - run: yarn install --frozen-lockfile

      - run: npx nx run-many --all -t lint test build

      - name: Trigger API Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          curl ${{ secrets.RENDER_API_DEPLOYMENT_URL }}

      - name: Trigger Client Deployment
        if: github.ref == 'refs/heads/main'
        run: |
          curl ${{ secrets.RENDER_CLIENT_DEPLOYMENT_URL }}
